// ========================================
// MÓDULO DE DADOS
// Gerencia dados simulados e dados atuais
// ========================================

// const dadosSimulados = {
//   imoveis: [
//     {
//       id: 1,
//       codigo: "IMV001",
//       nome: "Apartamento Luxo Centro",
//       proprietario: "João Silva",
//       tipo: "apartamento",
//       cidade: "São Paulo",
//       valor: 850000,
//       status: "aprovado",
//       quartos: 3,
//       banheiros: 2,
//       area: 120,
//     },
//     {
//       id: 2,
//       codigo: "IMV002",
//       nome: "Casa com Piscina",
//       proprietario: "Maria Santos",
//       tipo: "casa",
//       cidade: "Campinas",
//       valor: 1200000,
//       status: "aprovado",
//       quartos: 4,
//       banheiros: 3,
//       area: 250,
//     },
//     {
//       id: 3,
//       codigo: "IMV003",
//       nome: "Terreno Comercial",
//       proprietario: "Pedro Costa",
//       tipo: "terreno",
//       cidade: "Santos",
//       valor: 450000,
//       status: "pendente",
//       quartos: 0,
//       banheiros: 0,
//       area: 500,
//     },
//     {
//       id: 4,
//       codigo: "IMV004",
//       nome: "Sala Comercial",
//       proprietario: "Ana Lima",
//       tipo: "comercial",
//       cidade: "São Paulo",
//       valor: 380000,
//       status: "pendente",
//       quartos: 0,
//       banheiros: 1,
//       area: 80,
//     },
//     {
//       id: 5,
//       codigo: "IMV005",
//       nome: "Cobertura Vista Mar",
//       proprietario: "Carlos Mendes",
//       tipo: "apartamento",
//       cidade: "Santos",
//       valor: 2500000,
//       status: "aprovado",
//       quartos: 5,
//       banheiros: 4,
//       area: 350,
//     },
//     {
//       id: 6,
//       codigo: "IMV006",
//       nome: "Casa Condomínio Fechado",
//       proprietario: "Juliana Rocha",
//       tipo: "casa",
//       cidade: "Campinas",
//       valor: 980000,
//       status: "pendente",
//       quartos: 3,
//       banheiros: 2,
//       area: 180,
//     },
//     {
//       id: 7,
//       codigo: "IMV007",
//       nome: "Apartamento Compacto",
//       proprietario: "Roberto Alves",
//       tipo: "apartamento",
//       cidade: "São Paulo",
//       valor: 420000,
//       status: "aprovado",
//       quartos: 2,
//       banheiros: 1,
//       area: 65,
//     },
//     {
//       id: 8,
//       codigo: "IMV008",
//       nome: "Galpão Industrial",
//       proprietario: "Empresa XYZ",
//       tipo: "comercial",
//       cidade: "Campinas",
//       valor: 1800000,
//       status: "pendente",
//       quartos: 0,
//       banheiros: 2,
//       area: 800,
//     },
//     {
//       id: 9,
//       codigo: "IMV009",
//       nome: "Chácara Recreio",
//       proprietario: "Fernando Dias",
//       tipo: "terreno",
//       cidade: "Campinas",
//       valor: 750000,
//       status: "reprovado",
//       quartos: 0,
//       banheiros: 0,
//       area: 2000,
//     },
//     {
//       id: 10,
//       codigo: "IMV010",
//       nome: "Loft Moderno",
//       proprietario: "Beatriz Souza",
//       tipo: "apartamento",
//       cidade: "São Paulo",
//       valor: 650000,
//       status: "pendente",
//       quartos: 1,
//       banheiros: 1,
//       area: 85,
//     },
//     {
//       id: 11,
//       codigo: "IMV011",
//       nome: "Casa Sobrado",
//       proprietario: "Marcos Ferreira",
//       tipo: "casa",
//       cidade: "Santos",
//       valor: 890000,
//       status: "aprovado",
//       quartos: 3,
//       banheiros: 3,
//       area: 200,
//     },
//     {
//       id: 12,
//       codigo: "IMV012",
//       nome: "Apartamento Garden",
//       proprietario: "Luciana Martins",
//       tipo: "apartamento",
//       cidade: "Campinas",
//       valor: 720000,
//       status: "pendente",
//       quartos: 3,
//       banheiros: 2,
//       area: 140,
//     },
//     {
//       id: 13,
//       codigo: "IMV013",
//       nome: "Ponto Comercial",
//       proprietario: "José Oliveira",
//       tipo: "comercial",
//       cidade: "São Paulo",
//       valor: 550000,
//       status: "pendente",
//       quartos: 0,
//       banheiros: 1,
//       area: 120,
//     },
//     {
//       id: 14,
//       codigo: "IMV014",
//       nome: "Casa Térrea",
//       proprietario: "Sandra Ribeiro",
//       tipo: "casa",
//       cidade: "Santos",
//       valor: 680000,
//       status: "aprovado",
//       quartos: 2,
//       banheiros: 2,
//       area: 150,
//     },
//     {
//       id: 15,
//       codigo: "IMV015",
//       nome: "Apartamento Duplex",
//       proprietario: "Ricardo Gomes",
//       tipo: "apartamento",
//       cidade: "São Paulo",
//       valor: 1100000,
//       status: "pendente",
//       quartos: 4,
//       banheiros: 3,
//       area: 180,
//     },
//     {
//       id: 16,
//       codigo: "IMV016",
//       nome: "Terreno Urbano",
//       proprietario: "Paula Castro",
//       tipo: "terreno",
//       cidade: "Campinas",
//       valor: 320000,
//       status: "pendente",
//       quartos: 0,
//       banheiros: 0,
//       area: 350,
//     },
//     {
//       id: 17,
//       codigo: "IMV017",
//       nome: "Studio Decorado",
//       proprietario: "Thiago Barros",
//       tipo: "apartamento",
//       cidade: "São Paulo",
//       valor: 380000,
//       status: "aprovado",
//       quartos: 1,
//       banheiros: 1,
//       area: 45,
//     },
//     {
//       id: 18,
//       codigo: "IMV018",
//       nome: "Casa Colonial",
//       proprietario: "Adriana Pinto",
//       tipo: "casa",
//       cidade: "Santos",
//       valor: 1450000,
//       status: "pendente",
//       quartos: 5,
//       banheiros: 4,
//       area: 320,
//     },
//   ],

//   usuarios: [
//     { id: 1, nome: "João Silva", email: "joao@email.com", tipo: "usuario", imoveis: 3, dataCadastro: "2024-01-15" },
//     { id: 2, nome: "Maria Santos", email: "maria@email.com", tipo: "corretor", imoveis: 8, dataCadastro: "2023-11-20" },
//     { id: 3, nome: "Pedro Costa", email: "pedro@email.com", tipo: "usuario", imoveis: 1, dataCadastro: "2024-02-10" },
//     { id: 4, nome: "Ana Lima", email: "ana@email.com", tipo: "corretor", imoveis: 5, dataCadastro: "2023-09-05" },
//     {
//       id: 5,
//       nome: "Carlos Mendes",
//       email: "carlos@email.com",
//       tipo: "usuario",
//       imoveis: 2,
//       dataCadastro: "2024-03-01",
//     },
//     { id: 6, nome: "Juliana Rocha", email: "juliana@email.com", tipo: "admin", imoveis: 0, dataCadastro: "2023-06-12" },
//     {
//       id: 7,
//       nome: "Roberto Alves",
//       email: "roberto@email.com",
//       tipo: "usuario",
//       imoveis: 1,
//       dataCadastro: "2024-01-28",
//     },
//   ],

//   mensagens: [
//     {
//       id: 1,
//       remetente: "João Silva",
//       assunto: "Dúvida sobre imóvel",
//       mensagem: "Gostaria de mais informações sobre o apartamento IMV001.",
//       data: "2024-10-15 14:30",
//       lida: false,
//     },
//     {
//       id: 2,
//       remetente: "Maria Santos",
//       assunto: "Aprovação pendente",
//       mensagem: "Quando meu imóvel será aprovado?",
//       data: "2024-10-14 10:15",
//       lida: false,
//     },
//     {
//       id: 3,
//       remetente: "Pedro Costa",
//       assunto: "Alteração de dados",
//       mensagem: "Preciso alterar o valor do meu terreno.",
//       data: "2024-10-13 16:45",
//       lida: true,
//     },
//     {
//       id: 4,
//       remetente: "Ana Lima",
//       assunto: "Agendamento de visita",
//       mensagem: "Cliente interessado em visitar a sala comercial.",
//       data: "2024-10-12 09:20",
//       lida: false,
//     },
//     {
//       id: 5,
//       remetente: "Carlos Mendes",
//       assunto: "Documentação",
//       mensagem: "Enviei os documentos solicitados por email.",
//       data: "2024-10-11 11:30",
//       lida: true,
//     },
//     {
//       id: 6,
//       remetente: "Juliana Rocha",
//       assunto: "Proposta recebida",
//       mensagem: "Recebi uma proposta para minha casa.",
//       data: "2024-10-10 15:00",
//       lida: false,
//     },
//   ],

//   agendamentos: [
//     {
//       id: 1,
//       cliente: "Lucas Ferreira",
//       imovel: "Apartamento Luxo Centro",
//       data: "2024-10-20",
//       horario: "14:00",
//       status: "confirmado",
//     },
//     {
//       id: 2,
//       cliente: "Camila Souza",
//       imovel: "Casa com Piscina",
//       data: "2024-10-21",
//       horario: "10:30",
//       status: "pendente",
//     },
//     {
//       id: 3,
//       cliente: "Rafael Oliveira",
//       imovel: "Cobertura Vista Mar",
//       data: "2024-10-22",
//       horario: "16:00",
//       status: "confirmado",
//     },
//     {
//       id: 4,
//       cliente: "Fernanda Lima",
//       imovel: "Loft Moderno",
//       data: "2024-10-23",
//       horario: "11:00",
//       status: "pendente",
//     },
//     {
//       id: 5,
//       cliente: "Bruno Costa",
//       imovel: "Casa Sobrado",
//       data: "2024-10-24",
//       horario: "15:30",
//       status: "cancelado",
//     },
//   ],

//   categorias: [
//     { id: 1, nome: "Casa", icone: "fa-home", quantidade: 5 },
//     { id: 2, nome: "Apartamento", icone: "fa-building", quantidade: 8 },
//     { id: 3, nome: "Terreno", icone: "fa-map", quantidade: 3 },
//     { id: 4, nome: "Comercial", icone: "fa-store", quantidade: 4 },
//   ],

//   comissoes: [
//     {
//       id: 1,
//       corretor: "Maria Santos",
//       imovel: "Apartamento Luxo Centro",
//       valor: 850000,
//       comissao: 42500,
//       data: "2024-10-01",
//     },
//     { id: 2, corretor: "Ana Lima", imovel: "Casa com Piscina", valor: 1200000, comissao: 60000, data: "2024-10-05" },
//     {
//       id: 3,
//       corretor: "Maria Santos",
//       imovel: "Cobertura Vista Mar",
//       valor: 2500000,
//       comissao: 125000,
//       data: "2024-10-08",
//     },
//     { id: 4, corretor: "Ana Lima", imovel: "Apartamento Compacto", valor: 420000, comissao: 21000, data: "2024-10-12" },
//   ],

//   atividades: [
//     {
//       tipo: "novo",
//       mensagem: "João Silva enviou um novo imóvel",
//       tempo: "5 minutos atrás",
//       icone: "fa-home",
//       cor: "#D4A843",
//     },
//     {
//       tipo: "aprovacao",
//       mensagem: "Imóvel IMV007 foi aprovado",
//       tempo: "1 hora atrás",
//       icone: "fa-check",
//       cor: "#4CAF50",
//     },
//     {
//       tipo: "usuario",
//       mensagem: "Novo usuário cadastrado: Lucas Ferreira",
//       tempo: "2 horas atrás",
//       icone: "fa-user",
//       cor: "#2196F3",
//     },
//     {
//       tipo: "mensagem",
//       mensagem: "Nova mensagem de Maria Santos",
//       tempo: "3 horas atrás",
//       icone: "fa-envelope",
//       cor: "#FF9800",
//     },
//     {
//       tipo: "agendamento",
//       mensagem: "Visita agendada para IMV001",
//       tempo: "5 horas atrás",
//       icone: "fa-calendar",
//       cor: "#9C27B0",
//     },
//   ],
// }

// Inicializa dadosAtuais como objeto vazio - será populado pela API
const dadosAtuais = {
  imoveis: [],
  usuarios: [],
  mensagens: [],
  agendamentos: [],
  categorias: [],
  cidades: [],
}

// Garante que dadosAtuais esteja no escopo global
if (typeof window !== "undefined") {
  window.dadosAtuais = dadosAtuais
}
